### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory '/dev/input/js1'

### ISSUE THREAD

**Issue by phantom-voltage** [foresto/joystickwake#2]
Since some Steam games require js0 to be the active controller, I've since set up a script to move plugged in joysticks to js0 under certain conditions. I noticed that my screensaver was being activated again, and when checking on joystickwake, I found the error in the title:

FileNotFoundError: [Errno 2] No such file or directory '/dev/input/js1'

I'm not sure if that's because before the udev rules and xboxdrv, the controller was first detected as js1 by joystickwake.

I know this problem isn't inherently related to joystickwake, but if I understood how joystickwake decides which js* device to monitor, I might be able to work around the issue. Any help is greatly appreciated!

**Comment by foresto** [comment]
Joystickwake watches udev for input devices with the ID_INPUT_JOYSTICK=1 property. When one appears, it opens the associated file and reads from it until udev reports a `remove` event.

If your script is making joystick device files disappear in some way that udev doesn't detect, I would expect it to cause problems for anything already using those devices (including joystickwake). Perhaps you should be assigning device file names with custom udev rules, rather than whatever your script is doing?
