### ISSUE TITLE
Bring 18.04 support back to the PPA

### ISSUE THREAD

**Issue by cobalt2727** [foresto/joystickwake#8]
If it's not too much trouble, could you start hosting update 18.04 builds on the PPA again? Tegra users (Jetson Nano, Nintendo Switch, etc) only officially have 18.04 supported by Nvidia right now, so having the PPA as an option instead of needing to manually compile it every so often for updates would be nice.

**Comment by foresto** [comment]
I don't have an 18.04 (bionic) system to test with, but since I haven't thought of a reason why it wouldn't work, I copied the latest package to that section of the PPA. If you test it and let me know that it works, I'll leave it there.

By the way, there's nothing to compile. Joystickwake is a single python file. The Ubuntu package just adds docs and a .desktop file for convenient startup. As long as you have python3-pyudev installed, you can always just save the latest version of [the program](https://raw.githubusercontent.com/foresto/joystickwake/master/joystickwake) to disk and run it directly.

**Comment by foresto** [comment]
@cobalt2727 have you tested the package that I recently published for 18.04? Does it work?

**Comment by cobalt2727** [comment]
I'll get access to my 18.04 machine again in about a week and a half, I'll let you know then

**Comment by cobalt2727** [comment]
I can get more eyes on it if needed, but it seems like it's working well!
